### ISSUE TITLE
tobytes: TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by jixunmoe** [nukemiko/libtakiyasha#1]
https://github.com/nukemiko/libtakiyasha/blob/e99e6a6e2b6d53b53e5bb373acf0750bd3f27db5/src/libtakiyasha/typeutils.py#L142

Python 版本：

```text
Python 3.10.8
```

```
Traceback (most recent call last):
  File "Z:\test\create-qmc2-file.py", line 8, in <module>
    qmc = QMCv2.new(
  File "Z:\test\venv\lib\site-packages\libtakiyasha\qmc\__init__.py", line 412, in new
    cipher = HardenedRC4(make_random_ascii_string(512))
  File "Z:\test\venv\lib\site-packages\libtakiyasha\qmc\qmcdataciphers.py", line 169, in __init__
    self._key512 = tobytes(key512)
  File "Z:\test\venv\lib\site-packages\libtakiyasha\typeutils.py", line 142, in tobytes
    return bytes(byteslike)
TypeError: string argument without an encoding
```

**Comment by jixunmoe** [comment]
添加一个 elif 判断字符串就好了：

```diff
     elif isinstance(byteslike, bytes):
         return byteslike
+    elif isinstance(byteslike, str):
+        return bytes(byteslike, encoding='utf-8')
     else:
         return bytes(byteslike)
```

**Comment by nukemiko** [comment]
https://github.com/nukemiko/libtakiyasha/pull/2 应当已经修复了。

没有修改 `tobytes()`，因为它的设计目的是将输入的**类字节对象**转换为 `bytes`。它不会转换/encode `str` 类型，这是用户的工作。

导致这个 `TypeError` 的直接原因是 `make_random_ascii_string()` 的返回值未经 encode 就直接作为 key 传递给了下层 Cipher 构造器，而后者使用了 `tobytes()` 转换输入的 key。
